version: "3.9"
services:

  # MySQL DataBase
  db:
    image: mysql:8.0.42
    container_name: point-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cometrue
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 10s
      timeout: 5s
      retries: 5
  
  # Spring Boot API
  app:
    container_name: point-app
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/point?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=pointer
      - SPRING_DATASOURCE_PASSWORD=pointer
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-data: